### PR TITLE
[Swatch] Fix #3646 – Use fallback image when a child product has no image

### LINKED ISSUE #3646: Exception #0 (Exception): Warning: Array to string conversion in /var/www/html/vendor/magento/module-swatches/Helper/Data.php on line 200
### Preconditions

Magento Version : Magento 2.4.7-p4

ElasticSuite Version : 2.11.13

Environment : both

Third party modules : 

### Steps to reproduce

1. Add color swatch and enable filtering
2. Have some products with custom images for swatches, and some without swatch variant image
3. Filter by few colours

### Expected result

1. Filtering works

### Actual result
```
Exception #0 (Exception): Warning: Array to string conversion in /var/www/html/vendor/magento/module-swatches/Helper/Data.php on line 200
<pre>#1 array_diff_assoc() called at [vendor/magento/module-swatches/Helper/Data.php:200]
#2 Magento\Swatches\Helper\Data->loadFirstVariation() called at [vendor/magento/module-swatches/Helper/Data.php:232]
#3 Magento\Swatches\Helper\Data->loadFirstVariationWithImage() called at [vendor/smile/elasticsuite/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php:101]
#4 Smile\ElasticsuiteSwatches\Model\Plugin\ProductImage->loadSimpleVariation() called at [vendor/smile/elasticsuite/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php:47]
#5 Smile\ElasticsuiteSwatches\Model\Plugin\ProductImage->beforeGetImage() called at [vendor/magento/framework/Interception/Interceptor.php:121]
#6 Magento\Catalog\Block\Product\ListProduct\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#7 Magento\Catalog\Block\Product\ListProduct\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Block/Product/ListProduct/Interceptor.php:329]
```

I've looked into where array comes to in first place and I've found that in [`src/vendor/smile/elasticsuite/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php:79`](https://github.com/Smile-SA/elasticsuite/blob/7818f5d1b28c2ed8d7fc062b7d379cf0aa6515dd/src/module-elasticsuite-swatches/Model/Plugin/ProductImage.php#L80) there is condition that adds option ids to array, which becomes a bit of a mixture of labels and ids.

Below screenshot of 2 debugging dump lines added after line 80

```
$filterArray[$code][] = $this->swatchHelperData->getOptionIds($attribute, $value);
dump($filterArray);
dump($this->swatchHelperData->getOptionIds($attribute, $value));
```

Image

### PR DESCRIPTION
**Pull request by PierreGauthier**

### CODE REVIEW

File: src/module-elasticsuite-swatches/Helper/Swatches.php [hunk 1]
```diff
@@ -72,6 +73,36 @@ public function loadVariationByFallback(Product $parentProduct, array $attribute
         return $variation;
     }
 
+    /**
+     * Load first variation with image
+     * Override: Manage fallback on child product with when multiple swatches values are selected.
```
Comment (rbayet) [inline src/module-elasticsuite-swatches/Helper/Swatches.php]: "... product **with** when ..."
Are some words missing or this one is extra ?
