### PR TITLE
Fixes #2013 mass add products to category

### LINKED ISSUE #2013: Can't bulk add products to category
### Preconditions

This is a repeat of #414 which seems to be present in the latest release on Magento 2.4.1.

Magento Version : 2.4.1

ElasticSuite Version :2.10.3

Environment : Live / staging

Third party modules : None

### Steps to reproduce

1. Go to Products->Categories
2. Open tab "Products in Category"
3. Search for some products
4. Select all using "select all checkbox" in the top left corner of the table
5. Hit "Save"

### Expected result

1. Category saves with new product selection

### Actual result

1. An error occurs: Something went wrong while saving the category.

```
 SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`xxxxxx`.`catalog_category_product`, CONSTRAINT `CAT_CTGR_PRD_PRD_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`product_id`) REFERENCES `catalog_product_entity` (`entity_id`) ON DELETE CAS), query was: INSERT  INTO `catalog_category_product` (`category_id`,`product_id`,`position`) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?)
```

Note that it works fine if you select the products individually before saving, it only happens when selecting a

### PR DESCRIPTION
**Pull request by vahonc**

### CODE REVIEW

File: src/module-elasticsuite-virtual-category/view/adminhtml/web/js/component/catalog/category/form/assign-products.js [hunk 1]
```diff
@@ -44,8 +44,8 @@ define([
                 if (element.positionElement) {
                     element.positionElement.disabled = false;
                     categoryProducts.set(element.value, element.positionElement.value);
-                } else if (element.value && element.id) {
-                    // Override is here. Add the product to categoryProducts even if it does not have position field
+                } else if (parseInt(element.value, 10) > 0) {
```
Comment (rbayet) [inline src/module-elasticsuite-virtual-category/view/adminhtml/web/js/component/catalog/category/form/assign-products.js:47]: Please change to `if (!isNan(parseInt(element.value, 10))) {`, I'm more confident in the behavior of isNan than in the `>` comparison.

**Review by rbayet — CHANGES_REQUESTED** [review]

**Review by rbayet — APPROVED** [review]
