### PR TITLE
Fixes #1503 fix sorting in Visual Swatches attribute

### LINKED ISSUE #1503: Visual swatches values not displayed in the right order in the filters
When a filter is a visual swatch, its values won't respect the order defined in the attribute administration (for example: number of results).

### Preconditions
Have an attribute being a visual swatch, with multiple values.
Have each of those values return a different amount of products.

Magento Version : 2.3.2
ElasticSuite Version : 2.8.1
Environment : Production
Third party modules : None (tested in a vanilla Magento, with just ElasticSuite enabled, and Luma theme)

### Steps to reproduce
1. Set a visual swatch attribute values sort order (facet sort order) to "Result count"
2. Load a category page that display the previously configured attribute as a filter

### Expected result
1. The values are displayed in the set order, starting with the one that has the most results, ending with the one that has the least results.

### Actual result
1. The values are displayed following the admin manually set order.

### PR DESCRIPTION
**Pull request by androshchuk**

### CODE REVIEW

File: src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php [hunk 1]
```diff
@@ -26,6 +27,50 @@
...
+        }
+
+        $attributeOptions = [];
+        $attributeOptionsSort = [];
+
+        $sortingArr = [];
+        foreach ($this->filter->getItems() as $item) {
+            $sortingArr[] = $item['label'];
+        }
+
```
Comment (rbayet) [inline src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php]: 2) Explain that you are here building an array whose keys are the attribute option label and not option id as in the native method.

File: src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php [hunk 2]
```diff
@@ -26,6 +27,50 @@
...
+        foreach ($this->eavAttribute->getOptions() as $option) {
+            if ($currentOption = $this->getFilterOption($this->filter->getItems(), $option)) {
+                $attributeOptions[$option->getLabel()] = array_merge($currentOption, ['id' => $option->getValue()]);
+            } elseif ($this->isShowEmptyResults()) {
+                $attributeOptions[$option->getLabel()] = array_merge($this->getUnusedOption($option), ['id' => $option->getValue()]);
+            }
+        }
+
```
Comment (rbayet) [inline src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php]: 3. Hence this last part where you built the array with the attribute options in the expected orders with the attribute option ids this time as keys (because it's a requirement for the `getSwatchesByOptionsId` helper method.

File: src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php [hunk 3]
```diff
@@ -26,6 +27,50 @@
...
+        foreach (array_merge(array_flip($sortingArr), $attributeOptions) as $item) {
+            $attributeOptionsSort[$item['id']] = $item;
+        }
+
+        $attributeOptionIds = array_keys($attributeOptionsSort);
+
```
Comment (rbayet) [inline src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php]: You can remove this empty line.

**Comment by rbayet** [comment]
Requested some purely cosmetics/documentation changes.

File: src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php [hunk 4]
```diff
@@ -37,15 +40,20 @@ public function getSwatchData(): array
         }
 
         $attributeOptions = [];
+        // Collect parameter labels in the expected order
```
Comment (rbayet) [inline src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php]: A full stop (".") is required at the end of the sentence to avoid a phpcs error.

File: src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php [hunk 5]
```diff
@@ -37,15 +40,20 @@ public function getSwatchData(): array
...
         $attributeOptionsSort = [];
-
+        // Build an array whose keys are the attribute option label and not option id as in the native method
```
Comment (rbayet) [inline src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php]: A full stop (".") is required at the end of the sentence to avoid a phpcs error.

File: src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php (hunk 4 above)
Comment (androshchuk) [reply src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php]: sorry. my phpcs settings broke. I fixed phpcs and his errors
