### PR TITLE
Fixes #1728 Special chars support in thesaurus rules

### LINKED ISSUE #1728: Multi-words terms with quotation sign(") not handled by thesaurus
If a multi-word synonym or expansion rule contains Inch sign(") multiple times, indexing the thesaurus fails with the error
### Preconditions

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"failed to build synonyms"}],"type":"illegal_argument_exception","reason":"failed to build synonyms","caused_by":{"type":"parse_exception","reason":"Invalid synonym rule at line 38","caused_by":{"type":"illegal_argument_exception","reason":"term: 4\" to_5\" analyzed to a token (4\"_to_5\") with position increment != 1 (got: 0)"}}},"status":400}`

Magento Version : EE 2.3.4

ElasticSuite Version : ~2.8.0, 2.9.x-dev

Environment :  elasticsearch  6.8 

Third party modules : N/A

### Steps to reproduce

1. Create a new Thesaurus, active on all stores
2. Add a thesaurus name "4Inch to 5Inch"
3. Add the synonym terms _**4" to 5",4inch to 5inch**_

### Expected result

1. The Thesaurus index should be rebuilt

### Actual result

1. Thesaurus reindexing fails with the error mentionned above

### PR DESCRIPTION
**Pull request by rbayet**
as well as multiple space/hyphen separating characters.
Please note this only special characters related errors when indexing the thesaurus rules,
but does not offer any warranty that those special characters will be accurately matched
when those rules are applied.

### CODE REVIEW

File: src/module-elasticsuite-thesaurus/Model/Indexer/IndexHandler.php [hunk 1]
```diff
@@ -161,7 +161,7 @@ private function addAnalyzerSettings($settings, $type, $values)
     private function prepareSynonymFilterData($rows)
     {
         $rowMaper = function ($row) {
-            return preg_replace('/([\w])[\s-](?=[\w])/u', '\1_', $row);
+            return preg_replace('/([^\s-])[\s-]+(?=[^\s-])/u', '\1_', $row);
```
Comment (romainruaud) [inline src/module-elasticsuite-thesaurus/Model/Indexer/IndexHandler.php]: I am Romain Ruaud and I approve this regex.
