### PR TITLE
Fixes #1686 autocomplete with spaces

### LINKED ISSUE #1686: Search box: Suggestions are showing even when user enter 3 spaces.
### Preconditions

We have over 20 Categories and 40 products
Elasticsearch version = 6.8.6
Elasticsuite module setting on admin

Magento Version : 2.3.3 CE

ElasticSuite Version :

Environment : 2.8.3

Third party modules :
Vnecoms_Core
Vnecoms_Sms
Vnecoms_SmsKsaSms
Ced_SmsaShipping

### Steps to reproduce

1. Enter 3 spaces in search bar.
2. It will show some product list for blank spaces also

### Expected result

1. It should trim the actual keywords enter in the search box

### Actual result

1. [Screenshot, logs]
space suggestion

### PR DESCRIPTION
**Pull request by androshchuk**

### CODE REVIEW

File: src/module-elasticsuite-core/Model/Autocomplete/Terms/DataProvider.php [hunk 1]
```diff
@@ -97,17 +97,19 @@ public function getType()
...
             if ($this->configurationHelper->isEnabled($this->getType())) {
-                foreach ($collection as $item) {
-                    $resultItem = $this->itemFactory->create([
-                        'title' => $item->getQueryText(),
-                        'num_results' => $item->getNumResults(),
-                        'type'        => $this->getType(),
-                    ]);
-                    $this->items[] = $resultItem;
+                $collection = $this->getSuggestCollection();
+                if ($collection !== null) {
```
Comment (rbayet) [inline src/module-elasticsuite-core/Model/Autocomplete/Terms/DataProvider.php]: Perform the test `if ($this->queryFactory->get()->isQueryTextShort()) {` here and then initialize the collection.

File: src/module-elasticsuite-core/Model/Autocomplete/Terms/DataProvider.php [hunk 2]
```diff
@@ -118,10 +120,13 @@ public function getItems()
...
      *
-     * @return Collection
+     * @return Collection|null
      */
-    private function getSuggestCollection()
+    private function getSuggestCollection(): ?Collection
     {
+        if ($this->queryFactory->get()->isQueryTextShort()) {
+            return null;
+        }
```
Comment (rbayet) [inline src/module-elasticsuite-core/Model/Autocomplete/Terms/DataProvider.php]: To remove, please see previous comment.

File: src/module-elasticsuite-core/Model/Autocomplete/Terms/DataProvider.php [hunk 3]
```diff
@@ -118,10 +120,13 @@ public function getItems()
     /**
      * Retrieve suggest collection for query
      *
-     * @return Collection
+     * @return Collection|null
```
Comment (rbayet) [inline src/module-elasticsuite-core/Model/Autocomplete/Terms/DataProvider.php]: Please revert to `@return Collection`

File: src/module-elasticsuite-core/view/frontend/web/js/form-mini.js [hunk 4]
```diff
@@ -30,7 +30,6 @@ define([
     $.widget('smileEs.quickSearch', $.mage.quickSearch, {
         options: {
             autocomplete: 'off',
-            minSearchLength: 2,
```
Comment (romainruaud) [inline src/module-elasticsuite-core/view/frontend/web/js/form-mini.js]: I think this could be kept, for me this is acting as a fallback value, if we inject something else via the template it should override this "2".

Comment (romainruaud) [reply src/module-elasticsuite-core/view/frontend/web/js/form-mini.js]: But it should be tested

File: src/module-elasticsuite-core/view/frontend/web/js/form-mini.js [hunk 5]
```diff
@@ -206,7 +205,7 @@ define([
          * @private
          */
         _isEmpty : function(value) {
-            return value === null || value.trim().length === 0;
+            return value === null || value.trim().length < parseInt(this.options.minSearchLength, 10);
```
Comment (rbayet) [inline src/module-elasticsuite-core/view/frontend/web/js/form-mini.js]: Fallback to === 0; please so visibility of the fulltext search submit button is not impacted (we do not respect the min_query_length in fulltext search)

File: src/module-elasticsuite-core/view/frontend/web/js/form-mini.js (hunk 4 above)
Comment (rbayet) [reply src/module-elasticsuite-core/view/frontend/web/js/form-mini.js]: agreed
